// SONGS------------------------------------------------------
export const FETCH_SONGS = 'FETCH_SONGS'
export const FETCH_SONGS_START = 'FETCH_SONGS_START'
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS'
export const FETCH_SONGS_FAIL = 'FETCH_SONGS_FAIL'

// export const CREATE_SONG = 'CREATE_SONG'
// export const CREATE_SONG_START = 'CREATE_SONG_START'
// export const CREATE_SONG_SUCCESS = 'CREATE_SONG_SUCCESS'
// export const CREATE_SONG_FAIL = 'CREATE_SONG_FAIL'

// export const DELETE_SONG = 'DELETE_SONG'
// export const DELETE_SONG_START = 'DELETE_SONG_START'
// export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS'
// export const DELETE_SONG_FAIL = 'DELETE_SONG_FAIL'

// export const UPDATE_SONG = 'UPDATE_SONG'
// export const UPDATE_SONG_START = 'UPDATE_SONG_START'
// export const UPDATE_SONG_SUCCESS = 'UPDATE_SONG_SUCCESS'
// export const UPDATE_SONG_FAIL = 'UPDATE_SONG_FAIL'

// COLLECTIONS------------------------------------------------------
export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS'
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START'
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS'
export const FETCH_COLLECTIONS_FAIL = 'FETCH_COLLECTIONS_FAIL'

// export const CREATE_COLLECTION = 'CREATE_COLLECTION'
// export const CREATE_COLLECTION_START = 'CREATE_COLLECTION_START'
// export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS'
// export const CREATE_COLLECTION_FAIL = 'CREATE_COLLECTION_FAIL'

// export const DELETE_COLLECTION = 'DELETE_COLLECTION'
// export const DELETE_COLLECTION_START = 'DELETE_COLLECTION_START'
// export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS'
// export const DELETE_COLLECTION_FAIL = 'DELETE_COLLECTION_FAIL'

// export const UPDATE_COLLECTION = 'UPDATE_COLLECTION'
// export const UPDATE_COLLECTION_START = 'UPDATE_COLLECTION_START'
// export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS'
// export const UPDATE_COLLECTION_FAIL = 'UPDATE_COLLECTION_FAIL'

